- hosts: all
  tasks:
    - package: 
        name: httpd
        state: present

    - copy:
        src: sen.html
        dest: /var/www/html

    - service:
        name: httpd
        state: started

