Vagrant.configure("2") do |config|

  config.vm.define "ansible-c" do |ansible|
    ansible.vm.box = "geerlingguy/centos7"
	ansible.vm.network "private_network", ip: "192.168.100.12"
	ansible.vm.provider "virtualbox" do |vb|
    config.vm.provider "virtualbox" do |v|
       v.memory = 2048
       v.cpus = 2
    end
   end
  end

  config.vm.define "node01" do |node01|
    node01.vm.box = "geerlingguy/centos7"
	node01.vm.network "public_network", ip: "192.168.100.11"
    config.vm.provider "virtualbox" do |v|
        v.memory = 1048
        v.cpus = 2
     end
  end
  
  config.vm.define "node02" do |node02|
    node02.vm.box = "geerlingguy/centos7"
	node02.vm.network "public_network", ip: "192.168.100.12"
     config.vm.provider "virtualbox" do |v|
        v.memory = 1048
        v.cpus = 2
     end
  end

   config.vm.define "node03" do |node03|
    node03.vm.box = "ubuntu/bionic64"
        node03.vm.network "public_network", ip: "192.168.100.13"
     config.vm.provider "virtualbox" do |v|
        v.memory = 1048
        v.cpus = 2
     end
  end
end
